-- Oman Sea Risk Index thematic layer for QGIS / PostGIS.
-- Zone boundaries are indicative simulation geometries for this prototype;
-- they implement the six sensitivity levels in the supplied risk-index document.

CREATE TABLE IF NOT EXISTS sea_risk_index (
  risk_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  risk_level text NOT NULL,
  coefficient numeric(3,1) NOT NULL,
  area_name text NOT NULL,
  basis text NOT NULL,
  draw_order integer NOT NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL
);

-- Regenerate only this thematic layer; it does not change ship_position or ship_track.
DELETE FROM sea_risk_index;

INSERT INTO sea_risk_index
  (risk_level, coefficient, area_name, basis, draw_order, geom)
VALUES
  (
    '一级核心敏感区', 2.0,
    '穆桑代姆珊瑚礁、马西拉岛海龟产卵区、库鲁姆红树林',
    '生态保护价值最高', 60,
    ST_GeomFromText('MULTIPOLYGON(
      ((56.16 26.37,56.46 26.40,56.66 26.23,56.61 25.99,56.35 25.94,56.13 26.10,56.16 26.37)),
      ((58.91 20.87,59.24 20.88,59.39 20.64,59.31 20.35,59.05 20.27,58.88 20.52,58.91 20.87)),
      ((58.43 23.74,58.62 23.79,58.75 23.68,58.68 23.54,58.47 23.56,58.43 23.74))
    )', 4326)
  ),
  (
    '二级高度敏感区', 1.8,
    '哈拉尼亚特群岛、鲸类活动海域、海洋保护区',
    '生物多样性高', 50,
    ST_GeomFromText('MULTIPOLYGON(
      ((55.60 17.72,56.10 17.78,56.25 17.49,56.10 17.21,55.70 17.18,55.49 17.42,55.60 17.72)),
      ((54.65 17.35,55.35 17.46,55.70 17.15,55.52 16.80,54.84 16.75,54.52 17.01,54.65 17.35)),
      ((59.57 22.90,60.20 23.00,60.55 22.69,60.41 22.29,59.83 22.20,59.45 22.52,59.57 22.90))
    )', 4326)
  ),
  (
    '三级重要生态区', 1.5,
    '马斯喀特海岸及旅游海湾',
    '人口和经济价值高', 40,
    ST_GeomFromText('MULTIPOLYGON(
      ((58.15 24.00,58.59 24.00,59.02 23.76,59.00 23.48,58.61 23.38,58.23 23.59,58.15 24.00))
    )', 4326)
  ),
  (
    '四级资源敏感区', 1.2,
    '阿曼近海渔场',
    '渔业资源', 30,
    ST_GeomFromText('MULTIPOLYGON(
      ((56.72 24.75,57.30 24.70,57.51 24.28,57.20 23.98,56.70 24.14,56.55 24.49,56.72 24.75)),
      ((57.70 20.15,58.50 20.25,58.72 19.77,58.33 19.38,57.75 19.47,57.55 19.80,57.70 20.15)),
      ((53.92 17.35,54.72 17.47,55.12 17.06,54.92 16.62,54.18 16.58,53.79 16.90,53.92 17.35))
    )', 4326)
  ),
  (
    '五级交通敏感区', 1.0,
    '苏尔港、杜库姆港、塞拉莱港航道',
    '运输风险', 20,
    ST_GeomFromText('MULTIPOLYGON(
      ((59.45 22.77,60.18 22.84,60.39 22.56,60.13 22.33,59.49 22.40,59.30 22.59,59.45 22.77)),
      ((57.67 19.94,58.20 20.04,58.33 19.73,58.09 19.51,57.66 19.53,57.54 19.76,57.67 19.94)),
      ((53.95 17.08,54.48 17.17,54.67 16.88,54.44 16.63,53.99 16.70,53.83 16.88,53.95 17.08))
    )', 4326)
  ),
  (
    '六级低敏区域', 0.5,
    '阿曼外海深水区',
    '生态影响较小', 10,
    ST_GeomFromText('MULTIPOLYGON(
      ((60.40 24.15,62.20 23.60,64.30 22.35,65.20 20.40,64.70 18.40,62.20 17.30,59.90 17.82,59.15 19.78,59.72 21.80,60.40 24.15))
    )', 4326)
  );

CREATE INDEX IF NOT EXISTS sea_risk_index_geom_gix
  ON sea_risk_index USING gist (geom);

-- QGIS: add PostGIS layer sea_risk_index, geometry column geom, unique ID risk_id.
-- Categorize by risk_level.  Recommended fills (40--55% opacity):
-- 一级 #D73027; 二级 #FC8D59; 三级 #FEE08B;
-- 四级 #91CF60; 五级 #4575B4; 六级 #BFD3E6.
-- Sort by draw_order ascending so the low-risk offshore background stays behind.
