--
-- PostgreSQL database dump
--

\restrict OBhqEGWVggh5QT8kWPaybbcl4miRlmAFEUq1eOajfBu0c5WNxJexOgB8HNnDhAO

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: oil_spill_area; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oil_spill_area (
    id integer NOT NULL,
    event_id character varying(20),
    event_time timestamp without time zone,
    area_km2 numeric(10,2),
    level character varying(20),
    status character varying(30),
    geom public.geometry(Polygon,4326)
);


--
-- Name: oil_spill_area_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.oil_spill_area_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: oil_spill_area_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.oil_spill_area_id_seq OWNED BY public.oil_spill_area.id;


--
-- Name: oil_spill_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oil_spill_event (
    id integer NOT NULL,
    event_id character varying(20),
    event_time timestamp without time zone,
    source character varying(50),
    status character varying(30),
    geom public.geometry(Point,4326)
);


--
-- Name: oil_spill_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.oil_spill_event_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: oil_spill_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.oil_spill_event_id_seq OWNED BY public.oil_spill_event.id;


--
-- Name: sea_risk_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sea_risk_index (
    risk_id integer NOT NULL,
    risk_level text NOT NULL,
    coefficient numeric(3,1) NOT NULL,
    area_name text NOT NULL,
    basis text NOT NULL,
    draw_order integer NOT NULL,
    geom public.geometry(MultiPolygon,4326) NOT NULL,
    fill_hex character varying(7),
    display_opacity smallint
);


--
-- Name: sea_risk_index_risk_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sea_risk_index ALTER COLUMN risk_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sea_risk_index_risk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ship_position; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ship_position (
    id integer NOT NULL,
    mmsi character varying(20),
    ship_name character varying(100),
    ship_type character varying(50),
    longitude double precision,
    latitude double precision,
    speed double precision,
    course double precision,
    update_time timestamp without time zone,
    geom public.geometry(Point,4326)
);


--
-- Name: ship_position_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ship_position_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ship_position_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ship_position_id_seq OWNED BY public.ship_position.id;


--
-- Name: ship_track; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ship_track (
    id integer NOT NULL,
    mmsi character varying(20),
    ship_name character varying(100),
    longitude double precision,
    latitude double precision,
    speed double precision,
    course double precision,
    update_time timestamp without time zone,
    geom public.geometry(Point,4326),
    ship_type character varying(20)
);


--
-- Name: ship_track_backup_offshore; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ship_track_backup_offshore (
    id integer,
    mmsi character varying(20),
    ship_name character varying(100),
    longitude double precision,
    latitude double precision,
    speed double precision,
    course double precision,
    update_time timestamp without time zone,
    geom public.geometry(Point,4326),
    ship_type character varying(20)
);


--
-- Name: ship_track_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ship_track_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ship_track_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ship_track_id_seq OWNED BY public.ship_track.id;


--
-- Name: ship_track_lines; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.ship_track_lines AS
 SELECT mmsi,
    max((ship_name)::text) AS ship_name,
    max((ship_type)::text) AS ship_type,
    min(update_time) AS start_time,
    max(update_time) AS end_time,
    count(*) AS point_count,
    (public.st_makeline(geom ORDER BY update_time))::public.geometry(LineString,4326) AS geom
   FROM public.ship_track
  GROUP BY mmsi
 HAVING (count(*) >= 2);


--
-- Name: suspicious_ship; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suspicious_ship (
    id integer NOT NULL,
    mmsi character varying(20),
    ship_name character varying(100),
    reason character varying(200),
    risk_level character varying(20),
    geom public.geometry(Point,4326)
);


--
-- Name: suspicious_ship_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.suspicious_ship_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: suspicious_ship_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.suspicious_ship_id_seq OWNED BY public.suspicious_ship.id;


--
-- Name: warning_area; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warning_area (
    id integer NOT NULL,
    warning_name character varying(100),
    warning_level character varying(20),
    reason character varying(200),
    warning_time timestamp without time zone,
    geom public.geometry(Polygon,4326)
);


--
-- Name: warning_area_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.warning_area_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: warning_area_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.warning_area_id_seq OWNED BY public.warning_area.id;


--
-- Name: oil_spill_area id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oil_spill_area ALTER COLUMN id SET DEFAULT nextval('public.oil_spill_area_id_seq'::regclass);


--
-- Name: oil_spill_event id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oil_spill_event ALTER COLUMN id SET DEFAULT nextval('public.oil_spill_event_id_seq'::regclass);


--
-- Name: ship_position id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ship_position ALTER COLUMN id SET DEFAULT nextval('public.ship_position_id_seq'::regclass);


--
-- Name: ship_track id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ship_track ALTER COLUMN id SET DEFAULT nextval('public.ship_track_id_seq'::regclass);


--
-- Name: suspicious_ship id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspicious_ship ALTER COLUMN id SET DEFAULT nextval('public.suspicious_ship_id_seq'::regclass);


--
-- Name: warning_area id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warning_area ALTER COLUMN id SET DEFAULT nextval('public.warning_area_id_seq'::regclass);


--
-- Name: oil_spill_area oil_spill_area_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oil_spill_area
    ADD CONSTRAINT oil_spill_area_pkey PRIMARY KEY (id);


--
-- Name: oil_spill_event oil_spill_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oil_spill_event
    ADD CONSTRAINT oil_spill_event_pkey PRIMARY KEY (id);


--
-- Name: sea_risk_index sea_risk_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sea_risk_index
    ADD CONSTRAINT sea_risk_index_pkey PRIMARY KEY (risk_id);


--
-- Name: ship_position ship_position_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ship_position
    ADD CONSTRAINT ship_position_pkey PRIMARY KEY (id);


--
-- Name: ship_track ship_track_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ship_track
    ADD CONSTRAINT ship_track_pkey PRIMARY KEY (id);


--
-- Name: suspicious_ship suspicious_ship_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspicious_ship
    ADD CONSTRAINT suspicious_ship_pkey PRIMARY KEY (id);


--
-- Name: warning_area warning_area_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warning_area
    ADD CONSTRAINT warning_area_pkey PRIMARY KEY (id);


--
-- Name: sea_risk_index_geom_gix; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sea_risk_index_geom_gix ON public.sea_risk_index USING gist (geom);


--
-- Name: ship_position_geom_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ship_position_geom_idx ON public.ship_position USING gist (geom);


--
-- PostgreSQL database dump complete
--

\unrestrict OBhqEGWVggh5QT8kWPaybbcl4miRlmAFEUq1eOajfBu0c5WNxJexOgB8HNnDhAO
